---

name: super-linter

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run-tests
        run: python -m unittest validate_declarative_form_test.py -v
        shell: bash