---

name: run-tests

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate-declarative-form-test
        run: python -m unittest validate_declarative_form_test.py -v
        shell: bash
